<?php
// <Internal Doc Start>
/*
*
* @description: 
* @tags: 
* @group: 
* @name: Ampy — LED-kalkylator — CSS
* @type: css
* @status: published
* @created_by: 13
* @created_at: 2026-06-09 15:55:23
* @updated_at: 2026-07-09 23:56:00
* @is_valid: 1
* @updated_by: 13
* @priority: 10
* @run_at: wp_head
* @load_as_file: yes
* @load_in_block_editor: 
* @condition: {"status":"no","run_if":"assertive","items":[[]]}
*/
?>
<?php if (!defined("ABSPATH")) { return;} // <Internal Doc End> ?>
/* ==========================================================================
   AMPY LED CALCULATOR — SNIPPET 1 of 3: CSS
   Paste as a Fluent Snippets snippet of type 'CSS'.
   All COMPONENT styling is scoped under .ampy-calc. The file additionally sets
   two global lines: the @import for the fonts (below) and the 62.5% base (last).
   Generated by build-snippets.js — DO NOT EDIT here; change ../styles.css.
   ========================================================================== */

/* =============================================================================
   LED calculator — STYLES (matches Ampy's battery calculator, same design system)
   1rem = 10px (html font-size 62.5%). Tokens on .ampy-calc. BEM ampy-calc__*.
   ============================================================================= */

/* Fonts are self-hosted and emitted by the render (LED.php); the prototype's
   Google Fonts @import has been removed - no third-party font request. */

/* ── WordPress container context ─────────────────────────────────────────────
   The prototype sized itself off the VIEWPORT (@media). Inside a Bricks column
   the viewport is wide while the component is narrow, so viewport breakpoints
   misfire and desktop rules apply in a narrow slot. Breakpoint VALUES are
   unchanged; they are now evaluated against the component's own inline size.
   `.ampy-led-outer` is already emitted by the render, so it becomes the named
   container. Same pattern the EV calculator already uses.
   Must stay AFTER the @import above: a rule before an @import makes the browser
   discard that @import, and the fonts then fail silently. */
.ampy-led-outer{
  display:block; width:100%; max-width:100%;
  box-sizing:border-box; overflow-x:hidden;
  container-type:inline-size; container-name:ampy;
}
/* NOTE: this tool builds on Ampy's design-system base html{font-size:62.5%}
   (1rem = 10px) — same as the battery calculator. The global base is set by
   the host page/theme (or by <head> in the standalone version), NOT by this file,
   so that embedding in Bricks/WordPress does not affect the rest of the page. */
#ampyLed{
  /* Color — semantic tokens (light surface) */
  --bg-primary: rgb(247, 249, 251);
  --bg-surface: rgb(9, 11, 50);
  --bg-subtle: rgb(234, 239, 243);
  --text-primary: rgb(15, 18, 60);
  --text-secondary: rgb(86, 94, 130);
  --text-inverse: rgb(255, 255, 255);
  --action-primary: rgb(0, 169, 145);
  --action-secondary: rgb(28, 196, 175);
  --state-success: rgb(57, 194, 129);
  --state-error: rgb(214, 76, 76);
  --state-warning: rgb(240, 175, 56);
  --border-default: rgba(15, 18, 60, 0.12);
  --border-focus: rgb(0, 169, 145);

  /* On dark navy surface */
  --on-surface-text: rgba(255, 255, 255, 0.94);
  --on-surface-text-muted: rgba(255, 255, 255, 0.66);
  --on-surface-text-faint: rgba(255, 255, 255, 0.55); /* AA: supporting text on navy ~5:1 */
  --on-surface-border: rgba(255, 255, 255, 0.14);
  --on-surface-border-strong: rgba(255, 255, 255, 0.28);
  --on-surface-subtle-bg: rgba(255, 255, 255, 0.06);

  /* Chart (stacked bar) */
  --chart-stream-1: rgb(0, 169, 145);
  --chart-stream-2: rgb(57, 194, 129);
  --chart-stream-3: rgb(122, 208, 198);
  --chart-stream-4: rgb(160, 184, 196);
  /* Payback curve */
  --chart-line-loss: rgb(240, 175, 56);
  --chart-line-profit: rgb(0, 169, 145);
  --chart-zone-loss: rgba(240, 175, 56, 0.18);
  --chart-zone-profit: rgba(0, 169, 145, 0.16);

  /* Spacing */
  --spacing-xs: 0.5rem; --spacing-sm: 0.75rem; --spacing-md: 1rem;
  --spacing-lg: 1.5rem; --spacing-xl: 2rem; --spacing-2xl: 3rem; --spacing-3xl: 4rem;
  /* Radius */
  --radius-sm: 0.6rem; --radius-md: 1.2rem; --radius-lg: 2rem; --radius-full: 999rem;
  /* Shadow */
  --shadow-sm: 0 1px 2px rgba(15, 18, 60, 0.06);
  --shadow-md: 0 0.4rem 1.2rem rgba(15, 18, 60, 0.08);
  --shadow-lg: 0 1.6rem 4rem rgba(15, 18, 60, 0.14);
  /* Motion */
  --motion-fast: 150ms; --motion-normal: 300ms; --easing: cubic-bezier(0.2, 0, 0.2, 1);

  /* Type scale — TRUE fluid (vw-based slope, anchors 375→1280px, 1rem=10px).
     Makes the typography actually grow on desktop (a touch larger) while holding a
     deliberate mobile minimum. The previous formula grew in px and got stuck at min. */
  --fs-xs:  clamp(1.2rem, calc(1.159rem + 0.110vw), 1.3rem);
  --fs-sm:  clamp(1.3rem, calc(1.217rem + 0.221vw), 1.5rem);
  --fs-md:  clamp(1.6rem, calc(1.476rem + 0.331vw), 1.9rem);
  --fs-lg:  clamp(1.8rem, calc(1.551rem + 0.663vw), 2.4rem);
  --fs-xl:  clamp(2.1rem, calc(1.810rem + 0.773vw), 2.8rem);
  --fs-2xl: clamp(2.4rem, calc(1.986rem + 1.105vw), 3.4rem);
  --fs-3xl: clamp(2.8rem, calc(2.137rem + 1.768vw), 4.4rem);
  --fs-4xl: clamp(3.8rem, calc(3.054rem + 1.989vw), 5.6rem);

  --font-heading: "Plus Jakarta Sans", system-ui, sans-serif;
  --font-body: "Outfit", system-ui, sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, monospace;

  box-sizing: border-box;
  color: var(--text-primary);
  background: var(--bg-primary);
  font-family: var(--font-body);
  font-size: var(--fs-md);
  line-height: 1.5;
  font-weight: 400;
  -webkit-font-smoothing: antialiased;
}

#ampyLed *,
#ampyLed *::before,
#ampyLed *::after{ box-sizing: border-box; }

#ampyLed p,
#ampyLed h1,
#ampyLed h2,
#ampyLed h3{ margin: 0; }

#ampyLed :where(.ampy-calc button){ font: inherit; color: inherit; background: transparent; border: 0; cursor: pointer; }

#ampyLed a{ color: var(--action-primary); text-decoration: none; }

#ampyLed a:hover{ text-decoration: underline; }

#ampyLed .ampy-calc__t-mono{ font-family: var(--font-mono); font-feature-settings: "tnum" 1, "lnum" 1; }
/* Utility classes scoped to the widget so they do not clash with the host page */
#ampyLed .sr-only{ position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; border: 0; }

#ampyLed .is-hidden{ display: none !important; }
/* --- Layout --------------------------------------------------------------- */
#ampyLed .ampy-calc__container{
  max-width: 128rem; margin: 0 auto;
  padding: var(--spacing-xl) var(--spacing-lg);
  display: flex; flex-direction: column; gap: var(--spacing-2xl);
}

#ampyLed .ampy-calc__header{ display: flex; flex-direction: column; gap: var(--spacing-xs); }

#ampyLed .ampy-calc__header h1{
  font-family: var(--font-heading); font-size: var(--fs-2xl); line-height: 1.2;
  font-weight: 700; letter-spacing: -0.015em; max-width: 80rem;
}

#ampyLed .ampy-calc__header p{ color: var(--text-secondary); font-size: var(--fs-sm); max-width: 70rem; }

#ampyLed .ampy-calc__main{
  display: grid; grid-template-columns: minmax(0, 5fr) minmax(0, 7fr);
  gap: var(--spacing-xl); align-items: start;
}

#ampyLed .ampy-calc__result-stack{ display: flex; flex-direction: column; gap: var(--spacing-md); min-width: 0; }

#ampyLed .ampy-calc__card{ min-width: 0; max-width: 100%; }

@container ampy (max-width: 960px){
#ampyLed .ampy-calc__main{ grid-template-columns: minmax(0, 1fr); }}

@container ampy (max-width: 768px){
#ampyLed .ampy-calc__container{ padding: var(--spacing-lg) var(--spacing-md); gap: var(--spacing-xl); }}
/* --- Cards ---------------------------------------------------------------- */
#ampyLed .ampy-calc__card{
  background: var(--bg-primary); border: 1px solid var(--border-default);
  border-radius: var(--radius-lg); padding: var(--spacing-xl); box-shadow: var(--shadow-sm);
  display: flex; flex-direction: column; gap: var(--spacing-lg);
}

@container ampy (max-width: 600px){
#ampyLed .ampy-calc__card{ padding: var(--spacing-lg); }}

#ampyLed .ampy-calc__card--surface{
  background: var(--bg-surface); color: var(--text-inverse); border-color: transparent;
  box-shadow: var(--shadow-lg);
  /* Airy result card with even vertical rhythm (senior spacing) */
  padding: var(--spacing-3xl); gap: var(--spacing-2xl);
  background-image:
    radial-gradient(120% 60% at 90% -10%, rgba(0, 169, 145, 0.28), transparent 60%),
    radial-gradient(80% 50% at -10% 110%, rgba(57, 194, 129, 0.16), transparent 60%);
}

@container ampy (max-width: 600px){
#ampyLed .ampy-calc__card--surface{ padding: var(--spacing-xl) var(--spacing-lg); gap: var(--spacing-xl); }}
/* --- Tiers / fields ------------------------------------------------------- */
#ampyLed .ampy-calc__tier{ display: flex; flex-direction: column; gap: var(--spacing-md); }

#ampyLed .ampy-calc__tier--primary{ gap: var(--spacing-lg); }

#ampyLed .ampy-calc__tier + .ampy-calc__tier{
  margin-top: var(--spacing-lg); padding-top: var(--spacing-lg); border-top: 1px solid var(--border-default);
}

#ampyLed .ampy-calc__tier-label{
  font-size: var(--fs-sm); color: var(--text-secondary); font-weight: 600;
  text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: calc(-1 * var(--spacing-xs));
}

#ampyLed .ampy-calc__field{ display: flex; flex-direction: column; gap: var(--spacing-xs); }

#ampyLed .ampy-calc__field-row{ display: flex; align-items: center; justify-content: space-between; gap: var(--spacing-md); }

#ampyLed .ampy-calc__field-label-tiny{
  font-size: var(--fs-xs); color: var(--text-secondary); font-weight: 500; letter-spacing: 0.02em;
  display: inline-flex; align-items: center; gap: var(--spacing-xs);
}

#ampyLed .ampy-calc__field-label{
  font-family: var(--font-heading); font-size: var(--fs-sm); font-weight: 600;
  color: var(--text-primary); letter-spacing: 0.01em;
  display: inline-flex; align-items: center; gap: var(--spacing-xs);
}

#ampyLed .ampy-calc__field-hint{ font-size: var(--fs-xs); color: var(--text-secondary); }

#ampyLed .ampy-calc__field--solar{ background: var(--bg-subtle); padding: var(--spacing-sm) var(--spacing-md); border-radius: var(--radius-md); }
/* --- Selector (light source) ---------------------------------------------- */
#ampyLed .ampy-calc__selector{ position: relative; }

#ampyLed .ampy-calc__selector-button{
  display: flex; align-items: center; gap: var(--spacing-md); width: 100%;
  padding: var(--spacing-md); background: var(--bg-primary);
  border: 1px solid var(--border-default); border-radius: var(--radius-md);
  text-align: left; transition: border-color var(--motion-fast), box-shadow var(--motion-fast);
}

#ampyLed .ampy-calc__selector-button:hover{ border-color: var(--text-secondary); }

#ampyLed .ampy-calc__selector-button:focus-visible{ outline: 0; border-color: var(--border-focus); box-shadow: 0 0 0 3px rgba(0, 169, 145, 0.25); }

#ampyLed .ampy-calc__selector-img{
  width: 5.6rem; height: 5.6rem; border-radius: var(--radius-sm); background: var(--bg-subtle);
  display: flex; align-items: center; justify-content: center; flex-shrink: 0; overflow: hidden;
}

#ampyLed .ampy-calc__selector-img svg{ width: 60%; height: 60%; color: var(--text-secondary); }

#ampyLed .ampy-calc__selector-text{ display: flex; flex-direction: column; gap: 0.2rem; min-width: 0; flex: 1; }

#ampyLed .ampy-calc__selector-name{
  font-family: var(--font-heading); font-weight: 600; font-size: var(--fs-md); color: var(--text-primary);
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}

#ampyLed .ampy-calc__selector-best{ font-size: var(--fs-xs); color: var(--text-secondary); }

#ampyLed .ampy-calc__selector-chevron{ color: var(--text-secondary); flex-shrink: 0; transition: transform var(--motion-fast); }

#ampyLed .ampy-calc__selector[aria-expanded="true"] .ampy-calc__selector-chevron{ transform: rotate(180deg); }

#ampyLed .ampy-calc__selector-list{
  position: absolute; top: calc(100% + var(--spacing-xs)); left: 0; right: 0; z-index: 30;
  background: var(--bg-primary); border: 1px solid var(--border-default); border-radius: var(--radius-md);
  box-shadow: var(--shadow-lg); max-height: min(44rem, 60vh); overflow-y: auto; -webkit-overflow-scrolling: touch;
  overscroll-behavior: contain; padding: var(--spacing-xs); display: none;
}

#ampyLed .ampy-calc__selector[aria-expanded="true"] .ampy-calc__selector-list{ display: block; }

#ampyLed .ampy-calc__selector-group{
  font-size: var(--fs-xs); font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em;
  color: var(--text-secondary); padding: var(--spacing-sm) var(--spacing-sm) var(--spacing-xs);
}

#ampyLed .ampy-calc__selector-option{
  display: flex; align-items: center; justify-content: space-between; gap: var(--spacing-md);
  padding: var(--spacing-sm); border-radius: var(--radius-sm); width: 100%; text-align: left;
}

#ampyLed .ampy-calc__selector-option:hover,
#ampyLed .ampy-calc__selector-option--selected{ background: var(--bg-subtle); }

#ampyLed .ampy-calc__selector-option:focus-visible{ outline: 0; box-shadow: inset 0 0 0 2px var(--border-focus); }

#ampyLed .ampy-calc__selector-option .name{ font-size: var(--fs-sm); color: var(--text-primary); }

#ampyLed .ampy-calc__selector-option .meta{ font-family: var(--font-mono); font-size: var(--fs-xs); color: var(--text-secondary); white-space: nowrap; }

#ampyLed .ampy-calc__badge{
  display: inline-block; padding: 0.15rem var(--spacing-xs); background: transparent; color: var(--action-primary);
  border: 1px solid var(--action-primary); font-size: var(--fs-xs); font-weight: 600;
  border-radius: var(--radius-full); letter-spacing: 0.02em; white-space: nowrap;
}
/* --- Prominent value + custom slider -------------------------------------- */
#ampyLed .ampy-calc__field--prominent{ gap: var(--spacing-sm); }

#ampyLed .ampy-calc__value-prominent{
  font-family: var(--font-mono); font-weight: 700; color: var(--text-primary); font-size: var(--fs-xl);
  line-height: 1.3; letter-spacing: -0.01em; display: inline-flex; align-items: baseline; gap: 0.6rem;
}

#ampyLed .ampy-calc__value-prominent--sm{ font-size: var(--fs-md); }

#ampyLed .ampy-calc__value-unit{ font-size: var(--fs-sm); color: var(--text-secondary); font-weight: 500; font-family: var(--font-body); }

#ampyLed .ampy-calc__slider-wrap{ display: flex; flex-direction: column; gap: var(--spacing-sm); }

#ampyLed .ampy-calc__slider{ position: relative; height: 4.4rem; touch-action: none; }

#ampyLed .ampy-calc__slider-track{ position: absolute; top: 50%; left: 1.2rem; right: 1.2rem; height: 0.6rem; transform: translateY(-50%); background: var(--bg-subtle); border-radius: var(--radius-full); }

#ampyLed .ampy-calc__slider-fill{ position: absolute; top: 50%; left: 1.2rem; height: 0.6rem; transform: translateY(-50%); background: linear-gradient(90deg, var(--action-primary), var(--state-success)); border-radius: var(--radius-full); transition: width var(--motion-normal) var(--easing); }

#ampyLed .ampy-calc__slider-thumb{
  position: absolute; top: 50%; width: 2.4rem; height: 2.4rem; border-radius: var(--radius-full);
  background: var(--bg-primary); border: 0.3rem solid var(--action-primary); box-shadow: var(--shadow-md);
  transform: translate(-50%, -50%); transition: left var(--motion-normal) var(--easing); cursor: grab;
}

#ampyLed .ampy-calc__slider:active .ampy-calc__slider-thumb{ transform: translate(-50%, -50%) scale(1.08); cursor: grabbing; }

#ampyLed .ampy-calc__slider:focus-within .ampy-calc__slider-thumb{ box-shadow: var(--shadow-md), 0 0 0 4px rgba(0, 169, 145, 0.25); }

#ampyLed .ampy-calc__slider:focus-visible{ outline: 0; }

#ampyLed .ampy-calc__slider-ticks{ display: flex; justify-content: space-between; padding: 0 0.4rem; }

#ampyLed .ampy-calc__slider-tick{
  font-family: var(--font-mono); font-size: var(--fs-xs); color: var(--text-secondary);
  min-height: 3.2rem; display: inline-flex; align-items: center; justify-content: center;
  padding: 0.6rem 0.4rem; border-radius: var(--radius-sm);
  touch-action: manipulation; -webkit-tap-highlight-color: transparent; user-select: none; -webkit-user-select: none;
}

#ampyLed .ampy-calc__slider-tick:hover{ color: var(--text-primary); }

#ampyLed .ampy-calc__slider-tick--active{ color: var(--action-primary); font-weight: 700; }
/* --- Toggle / segmented / stepper ----------------------------------------- */
#ampyLed .ampy-calc__toggle{ display: inline-flex; background: var(--bg-subtle); border-radius: var(--radius-full); padding: 0.4rem; gap: 0.2rem; }

#ampyLed .ampy-calc__toggle-option{
  padding: 0.6rem var(--spacing-md); border-radius: var(--radius-full); font-family: var(--font-heading);
  font-weight: 600; font-size: var(--fs-sm); color: var(--text-secondary); min-width: 6.4rem;
  transition: background var(--motion-fast), color var(--motion-fast), box-shadow var(--motion-fast);
}

#ampyLed .ampy-calc__toggle-option:hover{ color: var(--text-primary); }

#ampyLed .ampy-calc__toggle-option[aria-pressed="true"]{ background: var(--action-primary); color: var(--text-inverse); box-shadow: var(--shadow-sm); }

#ampyLed .ampy-calc__toggle-option:focus-visible{ outline: 0; box-shadow: 0 0 0 3px rgba(0, 169, 145, 0.3); }

#ampyLed .ampy-calc__segmented{ display: grid; gap: 0.4rem; padding: 0.4rem; background: var(--bg-subtle); border-radius: var(--radius-md); }
/* Column count is explicit per control so the two segmented groups (which share
   this class) never influence each other: audience = 3, price area = 4. */
#ampyLed .ampy-calc__segmented--3{ grid-template-columns: repeat(3, minmax(0, 1fr)); }
#ampyLed .ampy-calc__segmented--4{ grid-template-columns: repeat(4, minmax(0, 1fr)); }
/* Fallback for any segmented without a modifier: one column per button. */
#ampyLed .ampy-calc__segmented:not([class*="--"]){ grid-auto-flow: column; grid-auto-columns: 1fr; }

/* ── Fill guard (Bricks / theme-proof) ───────────────────────────────────────
   The control is already a full-width 1fr grid, matching the prototype. But a
   page-builder or theme rule (on [role="group"], on button layout, or a
   shrink-wrapping ancestor) can make the grey track render at content width. These
   additive lines pin the field and the track to fill their card. They are no-ops
   when nothing interferes, so the prototype look is unchanged; they only bite when
   something outside this snippet would otherwise squeeze the control. */
#ampyLed .ampy-calc__field { width: 100%; align-items: stretch; }
#ampyLed .ampy-calc__segmented { width: 100%; box-sizing: border-box; justify-items: stretch; }
#ampyLed .ampy-calc__segmented-option { width: 100%; min-width: 0; }

#ampyLed .ampy-calc__segmented-option{
  padding: var(--spacing-sm) var(--spacing-xs); font-family: var(--font-heading); font-weight: 600;
  font-size: var(--fs-sm); color: var(--text-secondary); border-radius: var(--radius-sm); text-align: center;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis; min-height: 4rem;
  transition: background var(--motion-fast), color var(--motion-fast), box-shadow var(--motion-fast);
}

@container ampy (max-width: 380px){
#ampyLed .ampy-calc__segmented-option{ padding: var(--spacing-sm) 0.3rem; font-size: var(--fs-xs); }}

#ampyLed .ampy-calc__segmented-option:hover{ color: var(--text-primary); }

#ampyLed .ampy-calc__segmented-option[aria-pressed="true"]{ background: var(--bg-primary); color: var(--action-primary); box-shadow: var(--shadow-sm); }

#ampyLed .ampy-calc__segmented-option:focus-visible{ outline: 0; box-shadow: 0 0 0 3px rgba(0, 169, 145, 0.3); }

#ampyLed .ampy-calc__stepper{ display: inline-flex; align-items: center; background: var(--bg-subtle); border-radius: var(--radius-full); padding: 0.3rem; }

#ampyLed .ampy-calc__stepper-btn{ width: 3.6rem; height: 3.6rem; border-radius: var(--radius-full); color: var(--text-primary); font-weight: 700; font-size: var(--fs-lg); display: flex; align-items: center; justify-content: center; transition: background var(--motion-fast); }

#ampyLed .ampy-calc__stepper-btn:hover:not(:disabled){ background: var(--bg-primary); }

#ampyLed .ampy-calc__stepper-btn:disabled{ opacity: 0.4; cursor: not-allowed; }

#ampyLed .ampy-calc__stepper-value{ font-family: var(--font-mono); font-weight: 700; min-width: 4rem; text-align: center; color: var(--text-primary); font-size: var(--fs-md); }
/* Info tooltip */
#ampyLed .ampy-calc__tip{
  width: 1.6rem; height: 1.6rem; border-radius: var(--radius-full); background: transparent;
  border: 1px solid var(--border-default); color: var(--text-secondary); font-size: 1rem; font-weight: 700;
  font-family: var(--font-heading); display: inline-flex; align-items: center; justify-content: center;
  cursor: help; margin-left: var(--spacing-xs); flex-shrink: 0;
}

#ampyLed .ampy-calc__tip:hover,
#ampyLed .ampy-calc__tip:focus-visible{ background: var(--action-primary); color: var(--text-inverse); border-color: var(--action-primary); outline: 0; }

/* ── Kill any theme-injected CSS tooltip on the info buttons ──────────────────
   The tool renders its OWN tooltip as a JS element (.ampy-calc__tooltip, fixed,
   above the button). Some themes/plugins also style [data-tip] / [aria-label] /
   [title] with a ::before/::after that prints the text BELOW - that is the second,
   duplicated bubble. These lines remove that pseudo-tooltip inside the tool only. */
#ampyLed .ampy-calc__tip::before,
#ampyLed .ampy-calc__tip::after,
#ampyLed [data-tip]::before,
#ampyLed [data-tip]::after { content: none !important; display: none !important; }
/* Disclosure ("Avancerat" / "Så har vi räknat") */
#ampyLed .ampy-calc__disclosure{ border-top: 1px solid var(--border-default); padding-top: var(--spacing-md); }

#ampyLed .ampy-calc__disclosure-summary{ display: flex; align-items: baseline; gap: var(--spacing-xs); font-family: var(--font-heading); font-weight: 600; color: var(--text-primary); list-style: none; cursor: pointer; padding: var(--spacing-xs) 0; }

#ampyLed .ampy-calc__disclosure-summary::-webkit-details-marker{ display: none; }

#ampyLed .ampy-calc__disclosure-summary::after{ content: "▾"; margin-left: auto; color: var(--text-secondary); transition: transform var(--motion-fast); }

#ampyLed .ampy-calc__disclosure[open] .ampy-calc__disclosure-summary::after{ transform: rotate(180deg); }

#ampyLed .ampy-calc__disclosure-content{ padding-top: var(--spacing-md); display: flex; flex-direction: column; gap: var(--spacing-md); }
/* Inputs */
#ampyLed .ampy-calc__input,
#ampyLed .ampy-calc__select{
  width: 100%; font-family: var(--font-body); font-size: var(--fs-sm); padding: var(--spacing-sm) var(--spacing-md);
  border: 1px solid var(--border-default); border-radius: var(--radius-md); min-height: 4.8rem;
  background: var(--bg-primary); color: var(--text-primary);
}

#ampyLed .ampy-calc__input:focus-visible,
#ampyLed .ampy-calc__select:focus-visible{ outline: 0; border-color: var(--border-focus); box-shadow: 0 0 0 3px rgba(0, 169, 145, 0.2); }
/* --- Hero (dark surface) -------------------------------------------------- */
#ampyLed .ampy-calc__hero{ display: flex; flex-direction: column; gap: var(--spacing-sm); }

#ampyLed .ampy-calc__hero-eyebrow{ font-family: var(--font-heading); font-size: var(--fs-sm); font-weight: 600; color: var(--on-surface-text-muted); text-transform: uppercase; letter-spacing: 0.06em; }

#ampyLed .ampy-calc__hero-value{ font-family: var(--font-heading); font-size: var(--fs-4xl); line-height: 1.0; font-weight: 700; color: var(--text-inverse); letter-spacing: -0.03em; display: inline-flex; align-items: baseline; gap: 1.2rem; }

#ampyLed .ampy-calc__hero-unit{ font-family: var(--font-heading); font-size: var(--fs-xl); font-weight: 500; color: var(--on-surface-text-muted); letter-spacing: -0.01em; }

#ampyLed .ampy-calc__hero-sub{ color: var(--on-surface-text-muted); font-size: var(--fs-sm); }
/* Trio */
#ampyLed .ampy-calc__trio{
  display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); grid-template-rows: auto auto auto;
  grid-auto-flow: column; column-gap: var(--spacing-lg); row-gap: 0.2rem; align-items: baseline;
}

#ampyLed .ampy-calc__trio-label{ font-family: var(--font-body); font-size: var(--fs-xs); color: var(--on-surface-text-muted); font-weight: 600; letter-spacing: 0.04em; text-transform: uppercase; }

#ampyLed .ampy-calc__trio-value{ font-family: var(--font-heading); font-size: var(--fs-xl); font-weight: 700; line-height: 1.2; color: var(--text-inverse); letter-spacing: -0.015em; display: inline-flex; align-items: baseline; gap: 0.6rem; white-space: nowrap; }

#ampyLed .ampy-calc__trio-unit{ font-family: var(--font-body); font-size: var(--fs-sm); font-weight: 500; color: var(--on-surface-text-muted); }

#ampyLed .ampy-calc__trio-sub{ color: var(--on-surface-text-faint); font-size: var(--fs-xs); line-height: 1.5; align-self: start; }

@container ampy (max-width: 560px){
#ampyLed .ampy-calc__trio{ grid-template-columns: 1fr; grid-auto-flow: row; }

#ampyLed .ampy-calc__trio-label:not(:first-child){ margin-top: var(--spacing-md); }}
/* Margin 0 — the even flex gap (2xl) provides the rhythm; the line becomes a calm divider */
#ampyLed .ampy-calc__internal-divider{ height: 1px; background: var(--on-surface-border); border: 0; margin: 0; }
/* Energy bar (replaces revenue streams) */
#ampyLed .ampy-calc__evidence{ display: flex; flex-direction: column; gap: var(--spacing-sm); }

#ampyLed .ampy-calc__evidence-label{ font-family: var(--font-heading); font-size: var(--fs-sm); font-weight: 600; color: var(--on-surface-text-muted); text-transform: uppercase; letter-spacing: 0.06em; }

#ampyLed .ampy-calc__streams-bar{ width: 100%; height: 2.4rem; border-radius: var(--radius-full); background: var(--on-surface-subtle-bg); overflow: hidden; display: flex; }

#ampyLed .ampy-calc__streams-segment{ height: 100%; transition: width var(--motion-normal) var(--easing); }

#ampyLed .ampy-calc__evidence-caption{ color: var(--on-surface-text-muted); font-size: var(--fs-xs); }

#ampyLed .ampy-calc__evidence-caption strong{ color: var(--text-inverse); font-weight: 600; }
/* --- Buttons / CTA / email ------------------------------------------------ */
#ampyLed .ampy-calc__cta-stack{ display: flex; flex-direction: column; gap: var(--spacing-md); }

#ampyLed .ampy-calc__btn{ display: inline-flex; align-items: center; justify-content: center; gap: var(--spacing-xs); padding: var(--spacing-sm) var(--spacing-lg); border-radius: var(--radius-md); font-family: var(--font-heading); font-weight: 600; font-size: var(--fs-sm); min-height: 4.8rem; transition: opacity var(--motion-fast), background var(--motion-fast), box-shadow var(--motion-fast), transform var(--motion-fast); }

#ampyLed .ampy-calc__btn:hover{ opacity: 0.92; }

#ampyLed .ampy-calc__btn:active{ opacity: 0.82; transform: translateY(1px); }

#ampyLed .ampy-calc__btn:focus-visible{ outline: 0; box-shadow: 0 0 0 4px rgba(0, 169, 145, 0.35); }

#ampyLed .ampy-calc__btn--primary{ background: var(--action-primary); color: var(--text-inverse); box-shadow: var(--shadow-md); }

#ampyLed .ampy-calc__btn--lg{ padding: var(--spacing-sm) var(--spacing-xl); min-height: 5rem; font-size: var(--fs-sm); }

#ampyLed .ampy-calc__btn--block{ width: 100%; }

#ampyLed .ampy-calc__btn--outline{ background: transparent; color: var(--text-inverse); border: 0.15rem solid var(--on-surface-border-strong); }

#ampyLed .ampy-calc__btn svg{ width: 1.8rem; height: 1.8rem; }
/* --- Methodology ("Så har vi räknat") ----------------------------------- */
#ampyLed .ampy-calc__methodology{ background: var(--bg-primary); border: 1px solid var(--border-default); border-radius: var(--radius-md); padding: var(--spacing-md) var(--spacing-lg); }

#ampyLed .ampy-calc__methodology .ampy-calc__disclosure{ border-top: 0; padding-top: 0; }

#ampyLed .ampy-calc__methodology-stack{ display: flex; flex-direction: column; gap: var(--spacing-md); }

#ampyLed .ampy-calc__methodology-item{ display: flex; flex-direction: column; gap: var(--spacing-xs); }

#ampyLed .ampy-calc__methodology-item h3{ font-family: var(--font-heading); font-weight: 600; color: var(--text-primary); font-size: var(--fs-sm); letter-spacing: 0.01em; }

#ampyLed .ampy-calc__methodology-item p{ color: var(--text-secondary); font-size: var(--fs-xs); line-height: 1.5; }

#ampyLed .ampy-calc__methodology-item code{ align-self: flex-start; font-family: var(--font-mono); background: var(--bg-subtle); padding: 0.2rem var(--spacing-xs); border-radius: var(--radius-sm); color: var(--text-primary); font-weight: 600; font-size: var(--fs-xs); }

#ampyLed .ampy-calc__disclaimers{ margin-top: var(--spacing-md); padding-top: var(--spacing-md); border-top: 1px solid var(--border-default); color: var(--text-secondary); font-size: var(--fs-xs); line-height: 1.55; display: flex; flex-direction: column; gap: var(--spacing-sm); }
/* --- Slider: track the finger 1:1 during drag (no transition lag) --------- */
#ampyLed .ampy-calc__slider{ touch-action: none; user-select: none; -webkit-user-select: none; -webkit-tap-highlight-color: transparent; overscroll-behavior: contain; }

#ampyLed .ampy-calc__slider.is-dragging .ampy-calc__slider-thumb,
#ampyLed .ampy-calc__slider.is-dragging .ampy-calc__slider-fill{ transition: none; }
/* --- Lead form (expands below CTA, on dark surface) ----------------------- */
#ampyLed .ampy-calc__lead-form{ display: flex; flex-direction: column; gap: var(--spacing-md); }

#ampyLed .ampy-calc__lead-intro{ color: var(--on-surface-text-muted); font-size: var(--fs-sm); }

#ampyLed .ampy-calc__lead-grid{ display: grid; grid-template-columns: 1fr; gap: var(--spacing-md); }

@container ampy (min-width: 600px){
#ampyLed .ampy-calc__lead-grid{ grid-template-columns: 1fr 1fr; }}

#ampyLed .ampy-calc__lead-field{ display: flex; flex-direction: column; gap: var(--spacing-xs); min-width: 0; }

#ampyLed .ampy-calc__lead-field label{ font-size: var(--fs-xs); color: var(--on-surface-text); font-weight: 500; }

#ampyLed .ampy-calc__lead-field input{
  width: 100%; font-family: var(--font-body); font-size: var(--fs-sm);
  padding: var(--spacing-sm) var(--spacing-md); min-height: 4.8rem; border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.05); color: var(--text-inverse); border: 1px solid var(--on-surface-border-strong);
}

#ampyLed .ampy-calc__lead-field input::placeholder{ color: var(--on-surface-text-faint); }

#ampyLed .ampy-calc__lead-field input:focus-visible{ outline: 0; border-color: var(--action-secondary); box-shadow: 0 0 0 3px rgba(28, 196, 175, 0.35); }

#ampyLed .ampy-calc__lead-field input.is-invalid{ border-color: var(--state-error); }

#ampyLed .ampy-calc__hp{ position: absolute; left: -9999px; width: 1px; height: 1px; overflow: hidden; }

#ampyLed .ampy-calc__lead-msg{ font-size: var(--fs-sm); padding: var(--spacing-sm) var(--spacing-md); border-radius: var(--radius-md); }

#ampyLed .ampy-calc__lead-msg--ok{ background: rgba(57, 194, 129, 0.16); color: var(--text-inverse); border: 1px solid var(--state-success); }

#ampyLed .ampy-calc__lead-msg--err{ background: rgba(214, 76, 76, 0.16); color: var(--text-inverse); border: 1px solid var(--state-error); }

#ampyLed .ampy-calc__lead-optional{ color: var(--on-surface-text-faint); font-weight: 400; }

#ampyLed .ampy-calc__lead-consent{ display: flex; align-items: flex-start; gap: var(--spacing-sm); font-size: var(--fs-xs); color: var(--on-surface-text-muted); line-height: 1.5; }
/* Drawn checkbox (appearance:none) — always a visible border even where accent-color/
   the default box is invisible on a dark surface (iOS Safari <15.4, older Android WebView). */
#ampyLed .ampy-calc__lead-consent input{
  -webkit-appearance: none; appearance: none;
  width: 1.8rem; height: 1.8rem; min-width: 1.8rem; flex-shrink: 0; margin: 0; cursor: pointer;
  border: 0.15rem solid var(--on-surface-border-strong); border-radius: 0.4rem;
  background: rgba(255, 255, 255, 0.06);
  display: inline-grid; place-content: center;
  accent-color: var(--action-secondary); /* progressive enhancement */
}

#ampyLed .ampy-calc__lead-consent input::before{
  content: ""; width: 1rem; height: 1rem; transform: scale(0);
  transition: transform var(--motion-fast) var(--easing);
  background: var(--action-secondary);
  clip-path: polygon(14% 44%, 0 65%, 50% 100%, 100% 16%, 80% 0%, 43% 62%);
}

#ampyLed .ampy-calc__lead-consent input:checked{ border-color: var(--action-secondary); }

#ampyLed .ampy-calc__lead-consent input:checked::before{ transform: scale(1); }

#ampyLed .ampy-calc__lead-consent input:focus-visible{ outline: 0; box-shadow: 0 0 0 3px rgba(28, 196, 175, 0.4); }

#ampyLed .ampy-calc__lead-consent span{ flex: 1; min-width: 0; }

#ampyLed .ampy-calc__lead-consent input.is-invalid{ border-color: var(--state-error); box-shadow: 0 0 0 2px rgba(214, 76, 76, 0.5); }

#ampyLed .ampy-calc__lead-consent a{ color: var(--action-secondary); }

#ampyLed .ampy-calc__lead-fine{ font-size: var(--fs-xs); color: var(--on-surface-text-faint); text-align: center; }

#ampyLed .ampy-calc__lead-cancel{ font: inherit; color: var(--on-surface-text-muted); text-decoration: underline; padding: 0; }

#ampyLed .ampy-calc__lead-cancel:hover{ color: var(--text-inverse); }

#ampyLed .ampy-calc__lead-cancel:focus-visible{ outline: 0; box-shadow: 0 0 0 3px rgba(28, 196, 175, 0.4); border-radius: 0.3rem; }
/* --- Before/after comparison (electricity cost per year) ------------------ */
#ampyLed .ampy-calc__compare{ display: flex; flex-direction: column; gap: var(--spacing-sm); }

#ampyLed .ampy-calc__compare-row{ display: flex; align-items: center; gap: var(--spacing-md); }

#ampyLed .ampy-calc__compare-key{ width: 6rem; flex-shrink: 0; font-size: var(--fs-xs); font-weight: 600; }

#ampyLed .ampy-calc__compare-row--now .ampy-calc__compare-key{ color: var(--state-warning); }

#ampyLed .ampy-calc__compare-row--led .ampy-calc__compare-key{ color: var(--state-success); }

#ampyLed .ampy-calc__compare-track{ flex: 1; height: 2.4rem; background: var(--on-surface-subtle-bg); border-radius: var(--radius-full); overflow: hidden; }

#ampyLed .ampy-calc__compare-bar{ display: block; height: 100%; min-width: 1.6rem; border-radius: var(--radius-full); transition: width var(--motion-normal) var(--easing); }

#ampyLed .ampy-calc__compare-bar--now{ background: var(--chart-line-loss); }

#ampyLed .ampy-calc__compare-bar--led{ background: var(--state-success); }

#ampyLed .ampy-calc__compare-val{ min-width: 9rem; flex-shrink: 0; text-align: right; white-space: nowrap; font-size: var(--fs-sm); font-weight: 600; color: var(--text-inverse); }

@container ampy (max-width: 560px){
#ampyLed .ampy-calc__compare-key{ width: 5rem; }

#ampyLed .ampy-calc__compare-val{ min-width: 7.5rem; font-size: var(--fs-xs); }}
/* --- Info tooltip (floating) ---------------------------------------------- */
#ampyLed .ampy-calc__tooltip{
  position: fixed; z-index: 100; pointer-events: none;
  background: var(--bg-surface); color: var(--text-inverse);
  font-family: var(--font-body); font-size: var(--fs-xs); line-height: 1.45;
  padding: var(--spacing-sm) var(--spacing-md); border-radius: var(--radius-sm);
  box-shadow: var(--shadow-lg); border: 1px solid var(--on-surface-border-strong);
}
/* --- Animations / first-paint reveal -------------------------------------- */
@keyframes ampy-reveal{ from { opacity: 0; transform: translateY(0.6rem); } to { opacity: 1; transform: none; } }

#ampyLed .ampy-calc__hero,
#ampyLed .ampy-calc__trio,
#ampyLed .ampy-calc__compare,
#ampyLed .ampy-calc__cta-stack{ animation: ampy-reveal var(--motion-normal) var(--easing) both; }

#ampyLed .ampy-calc__hero{ animation-delay: 40ms; }

#ampyLed .ampy-calc__trio{ animation-delay: 120ms; }

#ampyLed .ampy-calc__compare{ animation-delay: 180ms; }

#ampyLed .ampy-calc__cta-stack{ animation-delay: 260ms; }

@media (prefers-reduced-motion: reduce){
#ampyLed *,
#ampyLed *::before,
#ampyLed *::after{ animation-duration: 0.001ms !important; transition-duration: 0.001ms !important; }}
/* --- Design-system base: 1rem = 10px ---------------------------------------
   Same base as Ampy's battery/EV calculator. ampy.se already runs this globally
   (no-op there). Placed LAST on purpose: a style rule before the @import above
   would invalidate the font import. If you scope this snippet to only the
   calculator pages, this line affects nothing else on the site. */
html{ font-size: 62.5%; }